/**
 * LMS Workflow Test Suite
 * 
 * This file tests the complete workflow:
 * 1. Batches creation and display
 * 2. AI Quiz generation
 * 3. Manual Quiz creation
 * 4. Quiz editing
 * 5. Quiz publishing
 * 6. Student quiz viewing and attempting
 */

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';

// Test Configuration
const TEST_CONFIG = {
  orgAdminToken: '',
  instructorToken: '',
  studentToken: '',
  organizationId: '',
  testBatchId: '',
  testCourseId: '',
  testQuizId: ''
};

// Helper: Make API requests
async function apiRequest(endpoint: string, options: any = {}) {
  const url = `${API_URL}${endpoint}`;
  const response = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers
    }
  });
  return await response.json();
}

// ============================================
// TEST 1: Batches Workflow
// ============================================
async function testBatchesWorkflow() {
  console.log('\n🧪 TEST 1: Batches Workflow');
  console.log('=====================================');
  
  try {
    // 1.1 List batches (should not fail)
    console.log('📋 1.1 Listing batches...');
    const listRes = await apiRequest('/api/college/admin/batches', {
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.orgAdminToken}` }
    });
    
    if (listRes.success) {
      console.log('✅ List batches: SUCCESS');
      console.log(`   Found ${listRes.data?.batches?.length || 0} batches`);
    } else {
      console.log('❌ List batches: FAILED');
      console.log('   Error:', listRes.message);
      return false;
    }
    
    // 1.2 Create batch
    console.log('\n📋 1.2 Creating test batch...');
    const createRes = await apiRequest('/api/college/admin/batches', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.orgAdminToken}` },
      body: JSON.stringify({
        name: 'Test Batch ' + Date.now(),
        code: 'TB' + Date.now().toString().slice(-4),
        programId: TEST_CONFIG.testCourseId,
        departmentId: '',
        year: 1,
        semester: 1,
        isActive: true
      })
    });
    
    if (createRes.success) {
      TEST_CONFIG.testBatchId = createRes.data?.batch?._id;
      console.log('✅ Create batch: SUCCESS');
      console.log('   Batch ID:', TEST_CONFIG.testBatchId);
    } else {
      console.log('❌ Create batch: FAILED');
      console.log('   Error:', createRes.message);
      return false;
    }
    
    // 1.3 Verify batch appears in list
    console.log('\n📋 1.3 Verifying batch appears in list...');
    const verifyRes = await apiRequest('/api/college/admin/batches', {
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.orgAdminToken}` }
    });
    
    const found = verifyRes.data?.batches?.find((b: any) => b._id === TEST_CONFIG.testBatchId);
    if (found) {
      console.log('✅ Batch appears in list: VERIFIED');
    } else {
      console.log('⚠️  Batch not immediately visible (may need refresh)');
    }
    
    return true;
  } catch (error) {
    console.log('❌ Batches workflow test failed:', error);
    return false;
  }
}

// ============================================
// TEST 2: AI Quiz Workflow
// ============================================
async function testAIQuizWorkflow() {
  console.log('\n🧪 TEST 2: AI Quiz Workflow');
  console.log('=====================================');
  
  try {
    // 2.1 Generate AI Quiz
    console.log('📋 2.1 Generating AI quiz...');
    const generateRes = await apiRequest('/api/quizzes/generate-ai', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` },
      body: JSON.stringify({
        course_id: TEST_CONFIG.testCourseId,
        topic: 'Test Topic for AI Quiz',
        difficulty: 'medium',
        num_questions: 3
      })
    });
    
    if (generateRes.success) {
      console.log('✅ AI Quiz generation: SUCCESS');
      console.log('   Generated', generateRes.data?.questions?.length, 'questions');
    } else {
      console.log('❌ AI Quiz generation: FAILED');
      console.log('   Error:', generateRes.message);
      return false;
    }
    
    // 2.2 Create quiz from AI generated content
    console.log('\n📋 2.2 Creating quiz from AI content...');
    const createRes = await apiRequest(`/instructor/courses/${TEST_CONFIG.testCourseId}/quizzes`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` },
      body: JSON.stringify({
        title: 'AI Generated Test Quiz',
        description: 'Test quiz generated by AI',
        questions: generateRes.data?.questions || [],
        pass_percentage: 60,
        max_attempts: 3
      })
    });
    
    if (createRes.success) {
      TEST_CONFIG.testQuizId = createRes.data?._id || createRes.data?.quiz?._id;
      console.log('✅ Create quiz: SUCCESS');
      console.log('   Quiz ID:', TEST_CONFIG.testQuizId);
    } else {
      console.log('❌ Create quiz: FAILED');
      console.log('   Error:', createRes.message);
      return false;
    }
    
    // 2.3 List quizzes
    console.log('\n📋 2.3 Listing quizzes...');
    const listRes = await apiRequest(`/api/quizzes?course_id=${TEST_CONFIG.testCourseId}`, {
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` }
    });
    
    if (listRes.success) {
      const quizzes = listRes.data?.quizzes || listRes.data || [];
      console.log('✅ List quizzes: SUCCESS');
      console.log(`   Found ${quizzes.length} quizzes`);
      
      const found = quizzes.find((q: any) => q._id === TEST_CONFIG.testQuizId);
      if (found) {
        console.log('   ✅ Created quiz appears in list');
      }
    } else {
      console.log('❌ List quizzes: FAILED');
    }
    
    return true;
  } catch (error) {
    console.log('❌ AI Quiz workflow test failed:', error);
    return false;
  }
}

// ============================================
// TEST 3: Manual Quiz Workflow
// ============================================
async function testManualQuizWorkflow() {
  console.log('\n🧪 TEST 3: Manual Quiz Workflow');
  console.log('=====================================');
  
  try {
    // 3.1 Create manual quiz
    console.log('📋 3.1 Creating manual quiz...');
    const createRes = await apiRequest(`/instructor/courses/${TEST_CONFIG.testCourseId}/quizzes`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` },
      body: JSON.stringify({
        title: 'Manual Test Quiz',
        description: 'Test quiz created manually',
        questions: [
          {
            question: 'What is 2+2?',
            options: ['1', '2', '4', '5'],
            correct_answer: 2
          },
          {
            question: 'What is the capital of France?',
            options: ['London', 'Berlin', 'Paris', 'Madrid'],
            correct_answer: 2
          }
        ],
        pass_percentage: 70,
        max_attempts: 2,
        status: 'draft'
      })
    });
    
    if (createRes.success) {
      const manualQuizId = createRes.data?._id || createRes.data?.quiz?._id;
      console.log('✅ Create manual quiz: SUCCESS');
      console.log('   Quiz ID:', manualQuizId);
      
      // 3.2 Edit the quiz
      console.log('\n📋 3.2 Editing quiz...');
      const editRes = await apiRequest(`/instructor/quizzes/${manualQuizId}`, {
        method: 'PUT',
        headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` },
        body: JSON.stringify({
          title: 'Manual Test Quiz (Edited)',
          description: 'Updated description',
          pass_percentage: 75
        })
      });
      
      if (editRes.success) {
        console.log('✅ Edit quiz: SUCCESS');
      } else {
        console.log('❌ Edit quiz: FAILED');
        console.log('   Error:', editRes.message);
      }
      
      // 3.3 Publish the quiz
      console.log('\n📋 3.3 Publishing quiz...');
      const publishRes = await apiRequest(`/api/quizzes/${manualQuizId}/publish`, {
        method: 'PATCH',
        headers: { 'Authorization': `Bearer ${TEST_CONFIG.instructorToken}` }
      });
      
      if (publishRes.success) {
        console.log('✅ Publish quiz: SUCCESS');
      } else {
        console.log('❌ Publish quiz: FAILED');
        console.log('   Error:', publishRes.message);
      }
    } else {
      console.log('❌ Create manual quiz: FAILED');
      console.log('   Error:', createRes.message);
      return false;
    }
    
    return true;
  } catch (error) {
    console.log('❌ Manual Quiz workflow test failed:', error);
    return false;
  }
}

// ============================================
// TEST 4: Student Quiz Workflow
// ============================================
async function testStudentQuizWorkflow() {
  console.log('\n🧪 TEST 4: Student Quiz Workflow');
  console.log('=====================================');
  
  try {
    // 4.1 Student views available quizzes
    console.log('📋 4.1 Student viewing quizzes...');
    const listRes = await apiRequest('/api/quizzes/student', {
      headers: { 'Authorization': `Bearer ${TEST_CONFIG.studentToken}` }
    });
    
    if (listRes.success) {
      console.log('✅ Student view quizzes: SUCCESS');
      console.log(`   Found ${listRes.data?.length || 0} available quizzes`);
    } else {
      console.log('❌ Student view quizzes: FAILED');
      console.log('   Error:', listRes.message);
      return false;
    }
    
    // 4.2 Student attempts quiz (if quiz exists)
    if (TEST_CONFIG.testQuizId) {
      console.log('\n📋 4.2 Student attempting quiz...');
      const attemptRes = await apiRequest(`/api/quizzes/${TEST_CONFIG.testQuizId}/submit`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${TEST_CONFIG.studentToken}` },
        body: JSON.stringify({
          answers: [
            { question_index: 0, selected_option: 2, time_spent_seconds: 10 },
            { question_index: 1, selected_option: 1, time_spent_seconds: 15 }
          ],
          started_at: new Date().toISOString()
        })
      });
      
      if (attemptRes.success) {
        console.log('✅ Quiz submission: SUCCESS');
        console.log('   Score:', attemptRes.data?.percentage || attemptRes.data?.score, '%');
        console.log('   Passed:', attemptRes.data?.passed ? 'YES' : 'NO');
      } else {
        console.log('❌ Quiz submission: FAILED');
        console.log('   Error:', attemptRes.message);
        // Don't fail the whole test if submission fails (might be out of attempts)
      }
    }
    
    return true;
  } catch (error) {
    console.log('❌ Student Quiz workflow test failed:', error);
    return false;
  }
}

// ============================================
// MAIN TEST RUNNER
// ============================================
export async function runAllTests(config: typeof TEST_CONFIG) {
  console.log('\n' + '='.repeat(50));
  console.log('🚀 LMS WORKFLOW TEST SUITE');
  console.log('='.repeat(50));
  
  // Update config
  Object.assign(TEST_CONFIG, config);
  
  const results = {
    batches: await testBatchesWorkflow(),
    aiQuiz: await testAIQuizWorkflow(),
    manualQuiz: await testManualQuizWorkflow(),
    studentQuiz: await testStudentQuizWorkflow()
  };
  
  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('📊 TEST SUMMARY');
  console.log('='.repeat(50));
  
  const allPassed = Object.values(results).every(r => r);
  
  Object.entries(results).forEach(([name, passed]) => {
    const icon = passed ? '✅' : '❌';
    console.log(`${icon} ${name}: ${passed ? 'PASSED' : 'FAILED'}`);
  });
  
  console.log('\n' + (allPassed ? '🎉 ALL TESTS PASSED!' : '⚠️ SOME TESTS FAILED'));
  console.log('='.repeat(50));
  
  return { allPassed, results };
}

// Export individual tests for specific testing
export {
  testBatchesWorkflow,
  testAIQuizWorkflow,
  testManualQuizWorkflow,
  testStudentQuizWorkflow
};

// If running directly
if (require.main === module) {
  // Example usage with test tokens
  const testConfig = {
    orgAdminToken: 'your-org-admin-token',
    instructorToken: 'your-instructor-token',
    studentToken: 'your-student-token',
    testCourseId: 'your-course-id'
  };
  
  runAllTests(testConfig).then(({ allPassed }) => {
    process.exit(allPassed ? 0 : 1);
  });
}
